#!/usr/bin/env node
/**
 * SilentPassUI 全站英文 UI 文案 → 简体中文（精确字面量替换）
 * 用法: node scripts/localizeToZh.mjs [--dry-run]
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SRC = path.join(__dirname, '../src')
const dryRun = process.argv.includes('--dry-run')

/** 按长度降序替换，避免短串误伤长串 */
export const ZH = {
	// Toast / errors
	'Unlock your wallet with your access password to claim coupons.': '请使用访问密码解锁钱包以领取优惠券。',
	'Unlock your wallet with your access password to continue.': '请使用访问密码解锁钱包后继续。',
	'Redeem link is missing a valid card address': '兑换链接缺少有效的卡地址',
	'Redeem link is invalid or wallet is not ready': '兑换链接无效或钱包未就绪',
	'Coupon link is invalid or wallet is not ready': '优惠券链接无效或钱包未就绪',
	'Coupon claim parameters are invalid': '优惠券领取参数无效',
	'Redeem submitted successfully': '兑换已提交成功',
	'Coupon open claim failed': '优惠券公开领取失败',
	'NFC card linked to your wallet.': 'NFC 卡已关联到您的钱包。',
	'Wallet is not ready yet': '钱包尚未就绪',
	'Top-up completed!': '充值完成！',
	'Failed to copy URL': '复制链接失败',
	'Redeem code created': '兑换码已创建',
	'Gift sent successfully': '赠送成功',
	'QR scan failed': '二维码扫描失败',
	'Card created successfully': '卡创建成功',
	'Image resized to <37MB': '图片已压缩至 37MB 以下',
	'Compressing to JPEG…': '正在压缩为 JPEG…',
	'Tier image uploaded': '等级图片已上传',
	'Share URL is unavailable': '分享链接不可用',
	'Claim URL copied': '领取链接已复制',
	'Could not share claim URL': '无法分享领取链接',
	'20 B-Units claimed!': '已领取 20 B-Unit！',
	'Create failed': '创建失败',
	'Upload failed': '上传失败',
	'Copy failed': '复制失败',
	'Link failed': '关联失败',
	'Redeem failed': '兑换失败',

	// Common actions
	'Confirm before submitting on-chain redeem.': '提交链上兑换前请确认。',
	'Confirm before submitting on-chain claim.': '提交链上领取前请确认。',
	'This redeem link must include a valid program card address.': '此兑换链接须包含有效的商户程序卡地址。',
	'Your reward has been added to your account.': '奖励已添加到您的账户。',
	'View transaction': '查看交易',
	'Missing card address': '缺少卡地址',
	'Redeem Successful': '兑换成功',
	'Redeem Failed': '兑换失败',
	'Redeem Code': '兑换码',
	'Coupon Claim': '领取优惠券',
	'Redeeming...': '兑换中…',
	'Claiming...': '领取中…',
	'Generating pay code…': '正在生成付款码…',
	'Generating Pay Code...': '正在生成付款码…',
	'Creating payment request…': '正在创建付款请求…',
	'Loading balances…': '正在加载余额…',
	'No recent transactions': '暂无最近交易',
	'No active passes': '暂无有效 Pass',
	'No active items': '暂无有效项目',
	'No physical keys linked.': '尚未关联实体密钥。',
	'Restore Wallet': '恢复钱包',
	'Activate Now': '立即激活',
	'Get Started with CashTrees': '开始使用 CashTrees',
	'Recent Activity': '最近动态',
	'View All': '查看全部',
	'Member Benefits': '会员权益',
	'Card Information': '卡信息',
	'Balance Details': '余额详情',
	'Physical Keys': '实体密钥',
	'Show Pay Code': '显示付款码',
	'Total Balance': '总余额',
	'Bind Physical Card': '绑定实体卡',
	'Manage Passes': '管理 Pass',
	'Featured Brands': '精选品牌',
	'Active Coupons': '有效优惠券',
	'Ongoing Coupons': '进行中优惠券',
	'My Brands': '我的品牌',
	'My Wallet': '我的钱包',
	'Smart Wallet': '智能钱包',
	'Express Pay': '快捷支付',
	'Main Wallet': '主钱包',
	'Wallet (USDC)': '钱包 (USDC)',
	'On Base': 'Base 链',
	'Add funds': '充值',
	'Cash out': '提现',
	'Top Up': '充值',
	'Gift': '赠送',
	'Send': '发送',
	'Pay': '支付',
	'Scan': '扫描',
	'Copy': '复制',
	'Share': '分享',
	'Print': '打印',
	'Close': '关闭',
	'Done': '完成',
	'Cancel': '取消',
	'Continue': '继续',
	'Confirm': '确认',
	'Submit': '提交',
	'Save': '保存',
	'Delete': '删除',
	'Edit': '编辑',
	'Back': '返回',
	'Next': '下一步',
	'Retry': '重试',
	'Refresh': '刷新',
	'Search': '搜索',
	'Discover': '发现',
	'Settings': '设置',
	'Notifications': '通知',
	'Privacy': '隐私',
	'Security': '安全',
	'Profile': '个人资料',
	'Messages': '消息',
	'Chat': '聊天',
	'History': '历史',
	'Wallet': '钱包',
	'Redeem': '兑换',
	'Claim': '领取',
	'Expired': '已过期',
	'Loading...': '加载中…',
	'Loading…': '加载中…',
	'Please wait...': '请稍候…',
	'Please wait…': '请稍候…',
	'Something went wrong': '出了点问题',
	'Try again': '重试',
	'Invalid Redeem Code': '无效的兑换码',
	'Activate Your Card.': '激活您的卡。',
	'Card Active!': '卡已激活！',
	'Verified Asset • Ready to Claim': '已验证资产 · 可领取',
	'Balance': '余额',
	'Security Status': '安全状态',
	'Fortified': '已加固',
	'Activation Pending': '待激活',
	'Powered by Beamio': 'Powered by Beamio',
	'Recording…': '记录中…',
	'Failed to record': '记录失败',
	'Requesting': '请求中',
	'Est. Receive': '预计到账',
	'Fee (0.8%)': '手续费 (0.8%)',
	'Funding Source': '资金来源',
	'Store Deposit': '门店充值',
	'Select Store Card': '选择门店卡',
	'Top Up Store Card': '充值门店卡',
	'Exchange Rate': '汇率',
	'From Vault (USDC)': '来自金库 (USDC)',
	'To Store Card (CAD)': '至门店卡 (CAD)',
	'Buy USDC via Coinbase': '通过 Coinbase 购买 USDC',
	'Buy USDC directly': '直接购买 USDC',
	'To Wallet': '至钱包',
	'Network': '网络',
	'Verified': '已验证',
	'Issuer': '发行方',
	'Standard': '标准',
	'Contract': '合约',
	'Hidden': '已隐藏',
	'Archived by you': '由您归档',
	'Universal Pass': '通用 Pass',
	'Pay QR': '付款码',
	'Hardware Security Layer': '硬件安全层',
	'Primary device': '主设备',
	'Store Balance (CAD)': '门店余额 (CAD)',
	"You've claimed 0.1 USDC": '您已领取 0.1 USDC',
	'Beamio Alpha Reward': 'Beamio Alpha 奖励',
	'Alliance Discount': '联盟折扣',
	'Gas-Free': '免 Gas',
	'Zero transaction fees on Beamio network.': 'Beamio 网络零交易手续费。',
	'Eligible for Store Discounts': '可享门店折扣',
	'Load Store Card via Cashier': '通过收银员充值门店卡',
	'Give physical cash to the issuing merchant': '向发行商户支付现金',
	'Use your USDC to fund a merchant card': '使用 USDC 为商户卡充值',
	'Show this code to the': '向',
	'issuing merchant': '发行商户',
	'and hand': '出示此码并交付',
	'Tap Scan to open camera and start scanning': '点击扫描打开相机开始扫码',
	'Activate AA wallet to use Pay Code': '激活 AA 钱包以使用付款码',
	'Express Pay (Smart Account)': '快捷支付（智能账户）',
	'No app download required yet.': '暂无需下载 App。',
	'Create a secure CashTrees wallet to claim this membership. No app download required yet.': '创建安全的 CashTrees 钱包以领取此会员。暂无需下载 App。',
	'Redemption complete. Funds available.': '兑换完成，资金已到账。',
	'REWARD RECEIVED': '奖励已到账',
	'Next: Secure Account Activation': '下一步：安全激活账户',
	'Generating Secure ID': '正在生成安全 ID',
	'Creating cryptographic keys': '正在创建加密密钥',
	'Finalizing Terminal': '正在完成终端设置',
	'Preparing user interface': '正在准备用户界面',
	'Create your Beamio ID': '创建您的 Beamio ID',
	'Your unique identity in the Beamio network. Use it to connect with friends and local brands.': '您在 Beamio 网络中的唯一身份。可用于连接好友与本地品牌。',
	'BeamioTag': 'BeamioTag',
	'username': '用户名',
	'Please enter a BeamioTag': '请输入 BeamioTag',
	'Use 3–20 letters, numbers, dots, or underscores': '请使用 3–20 个字母、数字、点或下划线',
	'@{{tag}} is already taken': '@{{tag}} 已被占用',
	'Network error. Try again.': '网络错误，请重试。',
	'This tag is available': '此标签可用',
	'Permanent. Cannot be changed later.': '永久有效，创建后不可更改。',
	'Secure Password': '安全密码',
	'Hide password': '隐藏密码',
	'Show password': '显示密码',
	'Strong security': '安全性强',
	'Building security': '安全性提升中',
	'Basic security': '基础安全性',
	'Set a secure password': '请设置安全密码',
	'At least 8 characters': '至少 8 个字符',
	'Upper and lowercase letters': '需含大小写字母',
	'At least one number': '至少包含一个数字',
	'Please fix:': '请修正：',
	'Vault': '保险库',
	'Encrypted Local Storage': '本地加密存储',
	'Sync': '同步',
	'Multi-device Continuity': '多设备连续使用',
	'Beamio is non-custodial. We cannot reset this password for you.': 'Beamio 为非托管钱包，我们无法为您重置此密码。',
	'By continuing, you agree to our': '继续即表示您同意我们的',
	'Terms of Service': '服务条款',
	' and ': ' 与 ',
	'Privacy Policy': '隐私政策',
	'Securing your identity...': '正在保护您的身份…',
	'DO NOT CLOSE THE APP DURING THIS PROCESS': '在此过程中请勿关闭 App',
	'Security Backup': '安全备份',
	'Your Recovery Code is your master key.': '恢复码是您的主密钥。',
	'If you lose your phone,': '若您丢失手机，',
	'this is the only way to get your funds back.': '这是取回资金的唯一方式。',
	'Unable to save to Photos. Please allow Photos access and try again.': '无法保存到相册。请允许访问相册后重试。',
	'Save to Photos': '保存到相册',
	'Copied': '已复制',
	'Copy Recovery Code': '复制恢复码',
	'I have securely saved my recovery code': '我已安全保存恢复码',
	'Deploying Smart Vault': '正在部署智能保险库',
	'Establishing storage on Base': '正在 Base 上建立存储',
	'Minting Membership': '正在铸造会员',
	'Adding card to your wallet': '正在将卡添加到您的钱包',
	'Verifying on Base L2': '正在 Base L2 上验证',
	'Confirming on blockchain': '正在链上确认',
	'Your community\'s heartbeat,': '社区脉搏，',
	'found in your phone.': '尽在掌中。',
	'Discover and connect with independent': '发现并与您喜爱的',
	'businesses you love.': '独立商户建立连接。',
	'Every tap tells a local story.': '每一次点击，都是本地故事。',
	'Get Started': '开始使用',
	'Already have a Beamio ID?': '已有 Beamio ID？',
	'Opened from home screen? Wallet data from Safari doesn\'t transfer. Use': '从主屏幕打开？Safari 中的钱包数据不会同步。请使用',
	'with your recovery code below.': '请在下方使用恢复码。',
	'Yesterday': '昨天',
	'VALID NOW': '现可领取',
	'NO EXPIRY': '无到期',
	'EXPIRED': '已过期',
	'SET END DATE': '请设置结束日期',
	'New NFT': '新建 NFT',
	'New Message': '新消息',
	'No messages yet': '暂无消息',
	'Type a message': '输入消息',
	'Type a message...': '输入消息…',
	'Send Message': '发送消息',
	'Update available': '有可用更新',
	'Reload to update': '重新加载以更新',
	'Image uploaded': '图片已上传',
	'Link': '链接',
	'OR': '或',
	'UID': 'UID',

	// Pay / History / Settings batch (2026-06)
	'Request': '请求',
	'Payment with NFC': 'NFC 支付',
	'Pay Me': '收款',
	'Pay bill': '支付账单',
	'Pay to': '付款给',
	'Paying from': '付款来源',
	'Payment with NFC': 'NFC 支付',
	'Payment QR': '付款二维码',
	'Payment Received': '已收款',
	'Payment Successful': '支付成功',
	'Payment': '支付',
	'PaymentNfc': 'NFC 支付',
	'PayRequest': '收款请求',
	'Show to pay': '出示付款码',
	'Show QR': '显示二维码',
	'SCAN USER': '扫描用户',
	'NFC Topup': 'NFC 充值',
	'ENTER CHARGE (CAD)': '输入收款金额 (CAD)',
	'Smart Routing Analysis': '智能路由分析',
	'Smart Routing (AA + EOA)': '智能路由 (AA + EOA)',
	'Detecting User': '识别用户',
	'Checking Membership': '检查会员',
	'Analyzing Assets': '分析资产',
	'Optimizing Route': '优化路径',
	'Sending transaction': '发送交易',
	'Waiting for transaction': '等待交易确认',
	'View on BaseScan': '在 BaseScan 查看',
	'Base Explorer': 'Base 浏览器',
	'Base Mainnet': 'Base 主网',
	'Bill Amount': '账单金额',
	'Member Discount (10%)': '会员折扣 (10%)',
	'Total Charge': '应付总额',
	'Total Paid': '已付总额',
	'Total Paid in USDC': 'USDC 实付',
	'PAYMENT DETAILS': '支付明细',
	'PAYMENT SOURCE': '支付来源',
	'Paid with $CCSA': '使用 $CCSA 支付',
	'Transaction IDs': '交易 ID',
	'Combined transfer': '组合转账',
	'Smart Account': '智能账户',
	'Main Vault': '主金库',
	'Main Vault (EOA)': '主金库 (EOA)',
	'Insufficient balance': '余额不足',
	'Insufficient B-Units': 'B-Unit 不足',
	'Go to Fuel Center': '前往 Fuel Center',
	'Successfully sent': '发送成功',
	'Cashcode Created': 'Cashcode 已创建',
	'Share this Beamio Cashcode as a link, QR, or redeem code.': '可将此 Beamio Cashcode 以链接、二维码或兑换码分享。',
	'It may take a few seconds to appear on-chain.': '链上显示可能需要几秒钟。',
	"What's this for?": '备注（选填）',
	'Your dynamic text goes here': '在此输入动态文字',
	'Write some detail…': '填写详情…',
	'Sent with Beamio - no gas fees.': '通过 Beamio 发送，免 Gas 费。',
	'Confirm & Sign': '确认并签名',
	'Remove gift envelope': '移除礼品信封',
	'Open camera': '打开相机',
	'Gift Envelope': '礼品信封',
	'Uploading image to IPFS, please wait': '正在上传图片至 IPFS，请稍候',
	'An error occurred while uploading the image to IPFS. Please try again later.': '上传图片至 IPFS 时出错，请稍后重试。',
	'Change >': '切换 >',
	'Secure • ': '安全 · ',
	'RPC Error!': 'RPC 错误！',
	'RPC错误': 'RPC 错误',
	'Unknow': '未知',
	'No Express Pay found. Please create or link a Express Pay first.': '未找到快捷支付，请先创建或关联快捷支付账户。',
	'Express Pay address cannot be the same as your EOA. Please create or link a Express Pay first.': '快捷支付地址不能与 EOA 相同，请先创建或关联快捷支付账户。',
	'Failed to get Express Pay address': '获取快捷支付地址失败',
	'Currency is required for accounting': '记账需要指定币种',
	'AAtoEOA failed': 'AA 转 EOA 失败',
	'AAtoEOA request failed': 'AA 转 EOA 请求失败',
	'B-Unit balance check failed': 'B-Unit 余额检查失败',
	'Sign failed': '签名失败',
	'Failed: ': '失败：',
	'Auto-refresh in ': '自动刷新 ',
	'Copy address': '复制地址',
	'Indexer History': '索引器历史',
	'Activity': '动态',
	'View all': '查看全部',
	'All Accounts': '全部账户',
	'Main Wallet (USDC)': '主钱包 (USDC)',
	'Express Pay (Assets)': '快捷支付（资产）',
	'Encrypted on CoNET L1': '加密于 CoNET L1',
	'No transactions this month': '本月暂无交易',
	'Pending': '待处理',
	'Incl': '含',
	'Unknown': '未知',
	'Top-up': '充值',
	'USDC Top-up': 'USDC 充值',
	'Merchant Payment': '商户支付',
	'Merchant': '商户',
	'Fuel Yield (1:100)': 'Fuel Yield (1:100)',
	'Request Expired': '请求已过期',
	'Request Canceled': '请求已取消',
	'Internal Transfer': '内部转账',
	'Express Pay → Main Wallet': '快捷支付 → 主钱包',
	'Main Wallet → Express Pay': '主钱包 → 快捷支付',
	'Withdraw from Express Pay': '从快捷支付提现',
	'Add to Express Pay': '充值至快捷支付',
	'Claimed': '已领取',
	'Gift Card': '礼品卡',
	'Gift': '礼品',
	'Transaction': '交易',
	'Beamio Transfer': 'Beamio 转账',
	'Beamio Payment': 'Beamio 支付',
	'Request ID: ': '请求 ID：',
	'Cancel request': '取消请求',
	'Recorded': '已记录',
	'Unknown error': '未知错误',
	'Request failed': '请求失败',
	'Network error': '网络错误',
	'Please enter a valid amount': '请输入有效金额',
	'No receiving address found': '未找到收款地址',
	'Cannot determine payee owner for B-Unit fee check': '无法确定收款方 B-Unit 费用检查的所有者',
	'Insufficient B-Units: payee needs ': 'B-Unit 不足：收款方需要 ',
	' for requestAccounting (balance: ': ' 用于 requestAccounting（余额：',
	' B-Units)': ' B-Unit）',
	'Your Beamio QR Kit': '您的 Beamio 二维码套件',
	'USDC · Any amount': 'USDC · 任意金额',
	'Beamio PayMe': 'Beamio 收款',
	'Demo': '演示',
	'Your Beamio profile': '您的 Beamio 资料',
	'Manage account, security and payment settings from the gear icon in the top right.': '点击右上角齿轮图标管理账户、安全与支付设置。',
	'Tap Following or Followers to see your connections.': '点击关注或粉丝查看您的社交关系。',
	'Following': '关注',
	'Followers': '粉丝',
	'Account Details': '账户详情',
	'Language & Currency': '语言与货币',
	'Backup Wallet': '备份钱包',
	'High Priority': '高优先级',
	'Recovery & Backup': '恢复与备份',
	'Help & Support': '帮助与支持',
	'On': '开启',
	'since ': '自 ',
	'Version ': '版本 ',
	'Beamio settings': 'Beamio 设置',
	'Beamio name': 'Beamio 名称',
	'Let other beamioers can @ you': '让其他 Beamio 用户可以通过 @ 找到您',
	'Choose from photos': '从相册选择',
	'Choose photo': '选择照片',
	'AI avatar': 'AI 头像',
	'Avatar preview': '头像预览',
	'AVATAR TEXT': '头像文字',
	'BEAMIO HANDLE': 'BEAMIO 账号',
	'FIRST NAME': '名',
	'LAST NAME': '姓',
	'PERMANENT': '永久',
	'Save Changes': '保存更改',
	'Change the letters to pick a different avatar.': '修改字母以选择不同头像。',
	'Confirm avatar text': '确认头像文字',
	'Change avatar': '更换头像',
	'Remove avatar image': '移除头像图片',
	'Music': '名',
	'Stadium': '姓',
	'Add Cash': '充值',
	'Redeemed Successfully': '兑换成功',
	'Confirmed': '已确认',
	'Redeem Asset': '兑换资产',
	'Mint to Express Pay (Smart Account)': '铸造至快捷支付（智能账户）',
	'Please enter a title': '请输入标题',
	'Request failed': '请求失败',
	' pending': ' 待处理',
	' more · tap Manage for full list': ' 更多 · 点击管理查看完整列表',
	'Done': '完成',
	'Hidden Passes': '已隐藏的 Pass',
	'Active Passes': '有效 Pass',
	'CCSA Card': 'CCSA 卡',
	'Transfer between Main Vault and Express Pay': '主金库与快捷支付互转',
	'$CCSA Balance': '$CCSA 余额',
	'USDC Top-up': 'USDC 充值',
	'Payer': '付款方',
	'OK': '确定',
	'Express Pay not found': '未找到快捷支付',
	'Insufficient B-Units: payer needs 2 B-Units for transfer fee (balance: ': 'B-Unit 不足：付款方需要 2 B-Unit 转账费（余额：',

	// Remaining batch 2 (long phrases only — avoid short keys that break state enums)
	'Balance': '余额',
	'Redeem Active List': '有效兑换码列表',
	' pending': ' 待处理',
	'Title (event name)': '标题（活动名称）',
	'Description (EIP-1155)': '描述 (EIP-1155)',
	'Valid from (optional)': '有效期起（选填）',
	'Valid until (optional)': '有效期止（选填）',
	'Max supply': '最大供应量',
	'Price (card currency, 0 = free)': '价格（卡币种，0 = 免费）',
	'Image (EIP-1155)': '图片 (EIP-1155)',
	'Background color (optional, e.g. #6366f1)': '背景色（选填，如 #6366f1）',
	'Select how you want to fund your balance': '选择充值方式',
	'Deposit Cash at Store': '门店现金充值',
	'Give cash to an Alliance cashier': '将现金交给 Alliance 收银员',
	'Buy USDC securely with debit/credit': '使用借记卡/信用卡安全购买 USDC',
	'Convert crypto to Network CA$': '将加密货币兑换为网络 CA$',
	'Waiting for cashier scan...': '等待收银员扫码...',
	'From (USDC)': '来自 (USDC)',
	'To (Network Balance)': '至（网络余额）',
	'Network Fee': '网络费',
	'Sponsored by CashTrees': '由 CashTrees 赞助',
	'Minting to AA...': '正在铸造至 AA...',
	'Executing Logic Hook': '正在执行 Logic Hook',
	'Stored Value Added': '储值已到账',
	'Just now': '刚刚',
	'Card address (optional)': '卡地址（选填）',
	'Universal Pass': '通用 Pass',
	'Total Balance': '总余额',
	'Link Invalidated': '链接已失效',
	'Card Voucher': '卡券',
	'Merged Voucher': '合并券',
	'Asset Merge & Upgrade': '资产合并与升级',
	'Smart Routing': '智能路由',
	'Transaction Type': '交易类型',
	'Program Card': '程序卡',
	'Payment Channel': '支付渠道',
	'Payment Method': '支付方式',
	'Received From': '收款自',
	'Paid To': '付款至',
	'Send To': '发送至',
	'Settlement Proof': '结算凭证',
	'Creation Proof': '创建凭证',
	'Base L2 (Value)': 'Base L2（价值）',
	'Base L2 (Pending)': 'Base L2（待处理）',
	'Awaiting Payment': '等待付款',
	'Hide Raw Data': '隐藏原始数据',
	'View Smart Receipt': '查看智能收据',
	'Loading full Transaction...': '正在加载完整交易...',
	'Copy raw data': '复制原始数据',
	'No signing key available': '无可用签名密钥',
	'Cancel failed': '取消失败',
	'Cash · Main Wallet (EOA)': 'Cash · 主钱包 (EOA)',
	'Cash • Main Wallet (EOA)': 'Cash · 主钱包 (EOA)',
	'Cash • Express Pay (AA)': 'Cash · 快捷支付 (AA)',
	'Points • Express Pay': 'Points · 快捷支付',
	'Coupon • Express Pay': 'Coupon · 快捷支付',
	'Voucher • Express Pay': 'Voucher · 快捷支付',
	'Voucher · Merged': '券 · 已合并',
	'View transaction': '查看交易',
	'Done & Go to Chat': '完成并前往聊天',
	'Generating Pay Code...': '正在生成付款码...',
	'Activate AA wallet to use Pay Code': '激活 AA 钱包以使用付款码',
	'Tap Scan to open camera and scan a Beamio payment QR code.': '点击扫描打开相机，扫描 Beamio 付款二维码。',
	'Creating payment request…': '正在创建收款请求…',
	'Express Pay (Smart Account)': '快捷支付（智能账户）',
	'Toggle theme': '切换主题',
	'Search all history': '搜索全部历史',
	'Fuel Yield (1:100)': '燃料收益 (1:100)',
	'Merchant Gift': '商户赠送',
	'Order locked. Someone is reviewing the checkout...': '订单已锁定，有人正在结账…',
	'Code is active. Waiting for payment.': '收款码有效，等待付款。',
	'Share Again': '再次分享',
	'Locked': '已锁定',
	'Checkout in progress': '结账进行中',
	'Request Withdrawn': '请求已撤回',
	'Awaiting payment': '等待付款',
	'Base L2 (Locked)': 'Base L2（已锁定）',
	'Send to Bank Account': '转至银行账户',
	'Cash Out': '提现',
	'Banking & Bridge': '银行与跨链',
	'Language': '语言',
	'Language & Currency': '语言与货币',
	'Exchange rate': '汇率',
	'Default stablecoin': '默认稳定币',
	'Tax %': '税率 %',
	'Payments settle in': '付款在 Base 上以',
	'Coinbase Oracle': 'Coinbase 预言机',
	'Done': '完成',

	// Remaining production UI (i18n catalog)
	'Unlock your wallet with your access password to top up.': '请使用访问密码解锁钱包以充值。',
	'Address copied': '地址已复制',
	'Available now': '现已可用',
	'Have a redeem link or QR code?': '有兑换链接或二维码？',
	'Any amount': '任意金额',
	'Fixed amount': '固定金额',
	'Early access · in testing': '早期体验 · 测试中',
	'Payment methods': '支付方式',
	'Get help': '获取帮助',
	'Top up with USDC': '使用 USDC 充值',
	'Loading coupons…': '正在加载优惠券…',
	'Loading reward tiers…': '正在加载奖励等级…',
	'Loading new cards…': '正在加载新卡…',
	'Card address is unavailable.': '卡地址不可用。',
	'Unlock gas-free payments & exclusive vouchers': '解锁免 Gas 支付与专属优惠券',
	'No vouchers yet. Visit Market to buy.': '暂无优惠券，请前往市场购买。',
	'Secured by Beamio': '由 Beamio 安全保护',
	'Tx hash': '交易哈希',
	'Creating payment request...': '正在创建付款请求…',
	'Ready to Scan': '准备扫描',
	'Your purchasing power breakdown': '您的购买力明细',
	'No discounts (USDC)': '无折扣（USDC）',
	'Fixed flat fee': '固定 flat 费用',
	'Receive to Activate': '收款以激活',
	'Show this code to cashier to pay.': '向收银员出示此码付款。',
	'Tap funded card to phone.': '将已充值的卡贴近手机。',
	'How to use': '使用方法',
	'Pay with CashTrees': '使用 CashTrees 付款',

	// WalletReadyScreen / EmbeddedPwaUpdateBanner
	'Digital Wallet': '数字钱包',
	'Main Account': '主账户',
	'ONE LAST STEP': '最后一步',
	'Activate Your Digital Wallet': '激活您的数字钱包',
	'Show to Cashier to Top up': '向收银员出示以充值',
	'Generate a unique code for physical terminal verification.': '生成唯一码供线下终端验证。',
	'Tap NFC Key to Sync': '贴近 NFC 密钥同步',
	'Hold your device near the Beamio station to auto-link.': '将设备靠近 Beamio 终端以自动关联。',
	'Claim Merchant Coupon': '领取商户优惠券',
	'Activate your account using a gift link or by scanning a voucher QR code.': '通过礼品链接或扫描优惠券二维码激活账户。',
	'Your wallet remains inactive for security until a hardware connection is established. This ensures only you can access your encrypted assets.': '为安全起见，在建立硬件连接前钱包保持未激活状态，确保只有您可访问加密资产。',
	'Close and finish later': '关闭并稍后完成',
	'Update failed': '更新失败',
	'Restarting…': '正在重启…',
	'Restart': '重启',
	'STEP 05 • FINAL': '步骤 05 · 完成',
	'Payment to': '付款至',
	'Update ready': '更新已就绪',
	'Current': '当前',

	// Home / 卡片面板
	'Total Purchasing Power': '总购买力',
	'USDC Balance': 'USDC 余额',
	'Merchant Assets': '商户资产',
	'Tap at any Beamio SoftPOS to pay seamlessly.': '在任意 Beamio SoftPOS 终端贴近即可顺畅付款。',
	'See all': '查看全部',
	'No merchant brands yet.': '暂无商户品牌。',
	'Gift merchant balance': '赠送商户余额',
	'USDC on Base': 'Base 上的 USDC',
	'Thank you for testing Beamio on Base. Your Beamio wallet has been funded with': '感谢您在 Base 上测试 Beamio。您的 Beamio 钱包已获得',
	'so you can try your first gasless payment.': '，供您体验首次免 Gas 付款。',
	'No merchant cards yet.': '暂无商户卡。',
	'Merchant card': '商户卡',
	'Owned': '已持有',
}

const SKIP_DIRS = new Set(['locales', 'ABI', 'assets'])
const SKIP_FILES = /(\.test\.|\.spec\.|sample\.tsx|_副本|index copy)/

function walk(dir, out = []) {
	for (const name of fs.readdirSync(dir)) {
		const p = path.join(dir, name)
		const st = fs.statSync(p)
		if (st.isDirectory()) {
			if (!SKIP_DIRS.has(name)) walk(p, out)
			continue
		}
		if (!/\.(tsx?|jsx?)$/.test(name) || SKIP_FILES.test(name)) continue
		out.push(p)
	}
	return out
}

function localizeContent(content) {
	let out = content
	const keys = Object.keys(ZH).sort((a, b) => b.length - a.length)
	for (const en of keys) {
		const zh = ZH[en]
		out = out.split(`'${en}'`).join(`'${zh}'`)
		out = out.split(`"${en}"`).join(`"${zh}"`)
		out = out.split(`\`${en}\``).join(`\`${zh}\``)
		// JSX text nodes
		out = out.split(`>${en}<`).join(`>${zh}<`)
		out = out.split(`>${en}</`).join(`>${zh}</`)
	}
	// Dynamic expiry / time patterns (regex)
	out = out.replace(/`EXPIRES IN \$\{([^}]+)\}D`/g, '`${$1} 天后过期`')
	out = out.replace(/`EXPIRES IN \$\{([^}]+)\}H`/g, '`${$1} 小时后过期`')
	out = out.replace(/`EXPIRES IN \$\{Math\.ceil\(delta \/ 86_400\)\}D`/g, '`${Math.ceil(delta / 86_400)} 天后过期`')
	out = out.replace(/`EXPIRES IN \$\{Math\.ceil\(delta \/ 3_600\)\}H`/g, '`${Math.ceil(delta / 3_600)} 小时后过期`')
	out = out.replace(/`EXPIRES IN \$\{Math\.max\(1, Math\.ceil\(delta \/ 60\)\)\}M`/g, '`${Math.max(1, Math.ceil(delta / 60))} 分钟后过期`')
	out = out.replace(/\$\{mins\}m ago/g, '${mins} 分钟前')
	out = out.replace(/\$\{hours\}h ago/g, '${hours} 小时前')
	// Pay / History template titles
	out = out.replace(/`Send to \$\{/g, '`发送至 ${')
	out = out.replace(/`Paid to \$\{/g, '`付款给 ${')
	out = out.replace(/`Sent to \$\{/g, '`发送至 ${')
	out = out.replace(/`Received from \$\{/g, '`收款自 ${')
	out = out.replace(/`Payment to \$\{/g, '`付款至 ${')
	out = out.replace(/`Requesting \$\{/g, '`请求中 ${')
	out = out.replace(/Insufficient B-Units: payer needs 2 B-Units for transfer fee \(balance: \$\{/g, 'B-Unit 不足：付款方需要 2 B-Unit 转账费（余额：${')
	out = out.replace(/Insufficient B-Units: payee needs \$\{/g, 'B-Unit 不足：收款方需要 ${')
	return out
}

const fileArgs = process.argv.slice(2).filter((a) => !a.startsWith('--'))
const targetFiles = fileArgs.length
	? fileArgs.map((f) => path.isAbsolute(f) ? f : path.join(SRC, f.replace(/^\.\//, '').replace(/^src\//, '')))
	: walk(SRC)

let changed = 0
for (const file of targetFiles) {
	if (!fs.existsSync(file)) {
		console.warn('Skip missing:', file)
		continue
	}
	const before = fs.readFileSync(file, 'utf8')
	const after = localizeContent(before)
	if (after !== before) {
		changed++
		if (!dryRun) fs.writeFileSync(file, after, 'utf8')
		console.log(dryRun ? '[dry-run] ' : '', path.relative(SRC, file))
	}
}
console.log(`\n${dryRun ? 'Would update' : 'Updated'} ${changed} file(s).`)
